# Generated by Django 3.1 on 2020-11-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会社名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='金額')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='受注名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.company', verbose_name='会社')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(default=0, verbose_name='個数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='受注')),
            ],
        ),
    ]
